<?php

    return [
        'sales_invoice_list' => "Sales invoice list",
        'invoices_list' => "invoices list",
        'date' => "Date",
        'due_date' => "Due date",
        'total_excl_tax' => "Total (Excl.Tax)",
        'total_incl_tax' => "Total (Incl.Tax)",
        'payment_received' => "Payment received",
        'remaining_balance' => "Remaining balance",
        'vat' => "VAT",
        'add_an_invoice' => "Add an invoice",
        'customer' => "Customer",
        'select_a_customer' => "Select a customer",
        'quantity' => "Quantity",
        'total_price' => "Total price",
        'discount' => "Discount",
        'discount_value' => "Discount value",
        'yes' => "Yes",
        'no' => "No",
        'purchase_price' => "Purchase price",
        'sale_prise' => "Sale price",
        'enter_the_article_purchase_prise' => "Enter the article purchase prise",
        'enter_the_article_purchase_prise_please' => "Enter the article purchase price please!",
        'enter_the_article_sale_prise' => "Enter the article sale prise",
        'enter_the_article_sale_prise_please' => "Enter the article sale prise please!",
        'enter_a_valid_price_please' => "Enter a valid price please!",
        'insert_an_article' => "Insert an article",
        'insert_a_service' => "Insert a service",
        'article' => "Article",
        'service' => "Service",

        'select_an_article' => "Select an article",
        'select_a_service' => "Select a service",

        'select_an_article_please' => "Select an article please!",
        'select_a_service_please' => "Select a service please!",

        'quantity_cannot_be_empty' => "Quantity cannot be empty",
        'margin_cannot_be_empty' => "Margin cannot be empty",

        'margin' => "Margin",

        'this_item_has_already_been_inserted' => "This item has already been inserted, please change the quantity on the table.",
        'apply_discount' => "Apply discount",

        'select_customer_please' => "Select customer please!",

        'added_an_invoice_in_the_functional_unit' => "added an invoice in the functional unit",
        'the_invoice_was_added_successfully' => "The invoice was added successfully!",

        'modified_an_invoice_in_the_functional_unit' => "modified an invoice in the functional unit",
        'the_invoice_was_successfully_modified' => "The invoice was successfully modified!",

        'invoice_details' => "Invoice details",

        'invoice_content' => "Invoice content",
        'payment_details' => "Payment details",
        'cash_in' => "Cash in",
        'print' => "Print",

        'record_a_payment' => "Record a payment",
        'the_amount_to_be_collected_cannot_be_greater_than_the_remaining_balance' => "The amount to be collected cannot be greater than the remaining balance.",
        'amount_cannot_be_empty' => "Amount cannot be empty",
        'select_a_payment_method' => "Select a payment method",
        'select_a_payment_method_please' => "Select a payment method please!",

        'collection_of_the_invoice' => "Collection of the invoice",
        'recorded_an_invoice_payment' => "recorded an invoice payment",
        'payment_registered_successfully' => "Payment registered successfully!",

        'deleted_an_invoice_in_the_functional_unit' => "deleted an invoice in the functional unit",
        'invoice_deleted_successfully' => "Invoice deleted successfully",

        'invoice_MAJ' => "INVOICE",
        'invoice_MIN' => "Invoice",
        'invoice_generated_by_EXADERP' => "Invoice generated by EXADERP",

        /**
         * Proforma invoice
         */
        'proforma_invoice_list' => "Proforma invoice list",
        'add_a_proforma_invoice' => "Add a proforma invoice",
        'added_a_new_proforma_invoice_in_the_functional_unit' => "added a new proforma invoice in the functional unit",
        'proforma_invoice_added_successfully' => "Proforma invoice added successfully!",
        'modified_a_proforma_invoice_in_the_functional_unit' => "modified a proforma invoice in the functional unit",
        'the_proforma_invoice_has_been_successfully_modified' => "The proforma invoice has been successfully modified!",

        'proforma_details' => "Proforma details",
        'proforma_invoice_MIN' => "Proforma invoice",
        'proforma_invoice_MAJ' => "PROFORMA INVOICE",

        'deleted_a_proforma_invoice' => "deleted a proforma invoice",
        'proforma_invoice_successfully_deleted' => "Proforma invoice successfully deleted!",

        'convert_to_simple_invoice' => "Convert to simple invoice",
        'add_a_new_contact' => "Add a new contact",
        'edit_contact' => "Edit contact",

        'please_include_at_least_one_item_in_the_invoice' => "Please include at least one item in the invoice",

        'delivery_notes_list' => "delivery notes list",
        'add_a_delivery_note' => "Add a delivery note",

        'serial_number' => "Serial number",
        'enter_a_serial_number' => "Enter a serial number",
        'enter_a_serial_number_please' => "Enter a serial number please!",
        'add_serial_number' => "Add serial number",
        'update_serial_number' => "Update serial number",

        'delivery_note_added_successfully' => "Delivery note added successfully!",
        'added_a_delivery_note' => "added a delivery note",

        'delivery_note_modified_successfully' => "Delivery note modified successfully",
        'modified_a_delivery_note' => "modified a delivery note",

        'delivery_note_details' => "Delivery note details",
        'deleted_a_delivery_note' => "deleted a delivery note",
        'delivery_note_successfully_deleted' => "Delivery note successfully deleted",

        'delivery_note_MAJ' => "DELIVERY NOTE",
        'for' => "For",
        'concern' => "Concern",
        'enter_the_invoice_subject' => "Enter the invoice subject",
        'please_enter_the_invoice_subject' => "Please enter the invoice subject",

        'entrance' => "Entrances",
        'entrance_list' => "Entrances list",

        'record_an_entrance' => "Record an entrance",
        'enter_the_entrance_description' => "Enter the entrance description",
        'enter_the_entrance_description_please' => "Enter the entrance description please!",
        'please_enter_the_entrance_amount' => "Please enter the entrance amount!",

        'collection' => "Collection",
        'recorded_an_entrance' => "Recorded an entrance",
        'entrance_recorded_successfully' => "Entrance recorded successfully!",
        'updated_an_entrance' => "updated an entrance",
        'entrance_updated_successfully' => "Entrance updated successfully!",

        'validity_of_the_offer' => "Validity of the offer",
        'days' => "Days",
        'payment_terms' => "Payment terms",
        'to_order' => "To order",
        'after_delivery' => "After delivery",

        'sentence' => "Sentence",
        'list' => "List",

        'add_a_note' => "Add a note",
        'add_a_note_please' => "Add a note please!",
        'bold' => "Bold",
        'italic' => "Italic",

        'preview' => "Preview",
        'note_added_successfully' => "Note added successfully!",
        'note_updated_successfully' => "Note updated successfully!",
        'note_deleted_successfully' => "Note deleted successfully!",
        'days_number' => "Days number",
        'payment' => "Payment",
        'invoice_reference' => "Invoice reference",

];
